// Build src/buzzer-bank.js from the checked clue files. Re-run it whenever a
// batch lands rather than hand-editing the module, so the module and the
// files it came from can never drift.
const fs = require("fs");
const ROOT = "D:/Appbuilder/kotoba-dojo/";

const FILES = fs.readdirSync(ROOT).filter((f) => /^buzzer-clues-.*.json$/.test(f)).sort();
const scopes = JSON.parse(fs.readFileSync(ROOT + "buzzer-scopes.json", "utf8"));
const specOf = new Map(scopes.map((s) => [s.id, s]));

const cats = [];
for (const f of FILES) {
  if (!fs.existsSync(ROOT + f)) continue;
  for (const c of JSON.parse(fs.readFileSync(ROOT + f, "utf8"))) cats.push(c);
}

const esc = (s) => JSON.stringify(String(s));
const SECTION_ORDER = ["arena", "staples", "wordplay", "geography", "history", "science", "culture", "everyday", "lifestyle"];
cats.sort((a, b) => {
  const sa = specOf.get(a.id)?.section || a.section, sb = specOf.get(b.id)?.section || b.section;
  return SECTION_ORDER.indexOf(sa) - SECTION_ORDER.indexOf(sb) || a.name.localeCompare(b.name);
});

let out = `/**
 * The Buzzer — the clue bank.
 *
 * Categories of five clues, grouped into the sections a board is chosen from.
 * A clue carries its own three wrong options, and they come from the same
 * family as the answer on purpose: a column whose decoys come from nowhere in
 * particular is a column where the right answer is obvious on sight, and
 * four-options-from-the-same-family is the only thing stopping a blind buzz
 * from being a good bet.
 *
 * clues[0] is row one, the cheapest clue. Difficulty climbs down the column.
 *
 * \`source\` is kept on the arena categories deliberately. They are claims
 * about this codebase, and a claim about code should say which line it came
 * from — the alternative is a quiz that confidently teaches players something
 * the program stopped doing two releases ago.
 *
 * GENERATED by scripts/build-bank.mjs from buzzer-clues-*.json. Edit those.
 */

export const SECTIONS = [
  { id: "arena", name: "The arena" },
  { id: "staples", name: "The staples" },
  { id: "wordplay", name: "Wordplay" },
  { id: "geography", name: "Geography" },
  { id: "history", name: "History" },
  { id: "science", name: "Science and nature" },
  { id: "culture", name: "Culture" },
  { id: "everyday", name: "Everyday life" },
  { id: "lifestyle", name: "Life and leisure" },
];

export const CATEGORIES = [
`;

for (const c of cats) {
  const spec = specOf.get(c.id);
  const section = spec?.section || c.section || "arena";
  const clues = [...c.clues].sort((a, b) => a.row - b.row);
  out += `  {\n    id: ${esc(c.id)}, name: ${esc(c.name)}, section: ${esc(section)},\n`;
  out += `    scope: ${esc(c.scope || spec?.scope || "")},\n    clues: [\n`;
  for (const q of clues) {
    out += `      { q: ${esc(q.q)},\n        a: ${esc(q.a)},\n        wrong: [${q.wrong.map(esc).join(", ")}]`;
    out += q.source ? `,\n        source: ${esc(q.source)} },\n` : ` },\n`;
  }
  out += `    ],\n  },\n`;
}

out += `];

export function categoryById(id) {
  return CATEGORIES.find((c) => c.id === id) || null;
}

export function categoriesIn(sectionId) {
  return CATEGORIES.filter((c) => c.section === sectionId);
}

/**
 * Every answer and wrong option anywhere in a column, which is what a clue
 * falls back on when its own three decoys are not enough to fill four
 * options. Drawing from the column rather than from the whole bank is the
 * point: the family holds.
 */
export function poolFor(category) {
  const out = [];
  for (const c of category?.clues || []) out.push(c.a, ...(c.wrong || []));
  return out;
}
`;

fs.writeFileSync(ROOT + "src/buzzer-bank.js", out);
console.log(`bank built: ${cats.length} categories, ${cats.length * 5} clues`);
for (const s of SECTION_ORDER) {
  const n = cats.filter((c) => (specOf.get(c.id)?.section || c.section) === s).length;
  if (n) console.log(`  ${s.padEnd(10)} ${n}`);
}
